version: 0.2
env:
  variables:
    ECR_REPO_NAME: docker-test
phases:
  pre_build:
    commands:
      - echo "hello"
      
      #ECR login
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}

      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAM}:latest"
  build:
    commands:
      - docker build -t my-nginx-image:latest .
  post_build:
    commands:
      - docker tag my-nginx-image:latest ${ECR_MAIN_URI}
      - docker push ${ECR_IMAGE_URI}